### PR TITLE
default Generic instance, expanded tabs to fix GHC warning

### PR DESCRIPTION
**Pull request by voidlizard**
- Added Generic instances deriving
- Expanded tabs to fix GHC warning (-Wtabs)

### CODE REVIEW

**Comment by singpolyma** [comment]
Maybe don't reformat all the code in my project? ;) Also, what do you need the Generic instance for? I believe defining that requires a GHC extension.

**Comment by voidlizard** [comment]
1) Generic is required for automatic serialization and other scrap-your-boilerplate stuff. Manual  wGeneric instances writing is quite complicated and pointless.  Yes, it's GHC extension, but are there a lot of other haskell compilers around?

2) I usually don't reformat anything, but GHC produces warnings on tabs

**Comment by singpolyma** [comment]
My GHC does not produce a warning on tabs, but if you tell me what switch I need to add to suppress the warning in your version I can do that :)

**Comment by voidlizard** [comment]
Ok, but what about deriving Generic?  Without it this change is pointless. If you accept this, I'd better make new pull request with tabs and warning switched off, if you still want keep tabs for identation.

**Comment by singpolyma** [comment]
I could be convinced to have the Generic instance. Do you have a specific use case?

**Comment by voidlizard** [comment]
Sure, I have a quite big structure serialized into ByteStrings to store in leveldb database, like:

```
data Hotel = Hotel { hoOID         :: OID
                   , hoDisplayName :: Name
                   , hoClass       :: HotelClass
                   , hoLocations   :: Set Location
                   , hoDescription :: Map LanguageCode Content
                   , hoCurrency    :: Currency
                   -- trunced
                   } deriving (Eq, Ord,Show,Generic)
instance Serialize Currency
instance Serialize ISO4217Currency
instance Serialize Hotel

```
It's all I have to do to have a Serialize instance of all my data to store them in ```ByteString```.
Serialize has built-in instances for Generic classes, it's quite convenient.

Also, there are ```Data.Generics.Uniplate.Operations``` for Generics and a lot of other generic stuff that makes life simpler.

**Comment by singpolyma** [comment]
I'm going to close this for now, since it's been so long

**Pull request closed without merging**
